
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'AVANZAR_CTMS AVANZAR_MTS AVANZAR_VLTS BEGIN CAMINAR CIRCULO CUADRADO DOT END GIRAR ID LPAREN MOONWALK NUMBER PLUS PROGRAM ROTAR RPAREN SEMICOLONprogram : PROGRAM ID BEGIN sentence_list END DOTsentence_list : sentence_list sentence\n                     | sentencesentence : instruction SEMICOLONinstruction : move_instr\n                   | draw_instrinstruction : instruction PLUS instructionmove_instr : girar\n                  | avanzar_vlts\n                  | avanzar_ctms\n                  | avanzar_mts\n                  | rotar\n                  | caminar\n                  | moonwalkgirar : GIRAR LPAREN NUMBER RPARENavanzar_vlts : AVANZAR_VLTS LPAREN NUMBER RPARENavanzar_ctms : AVANZAR_CTMS LPAREN NUMBER RPARENavanzar_mts : AVANZAR_MTS LPAREN NUMBER RPARENrotar : ROTAR LPAREN NUMBER RPARENcaminar : CAMINAR LPAREN NUMBER RPARENmoonwalk : MOONWALK LPAREN NUMBER RPARENdraw_instr : circulo\n                  | cuadradocirculo : CIRCULO LPAREN NUMBER RPARENcuadrado : CUADRADO LPAREN NUMBER RPAREN'
    
_lr_action_items = {'PROGRAM':([0,],[2,]),'$end':([1,41,],[0,-1,]),'ID':([2,],[3,]),'BEGIN':([3,],[4,]),'GIRAR':([4,5,6,29,30,31,],[19,19,-3,-2,-4,19,]),'AVANZAR_VLTS':([4,5,6,29,30,31,],[20,20,-3,-2,-4,20,]),'AVANZAR_CTMS':([4,5,6,29,30,31,],[21,21,-3,-2,-4,21,]),'AVANZAR_MTS':([4,5,6,29,30,31,],[22,22,-3,-2,-4,22,]),'ROTAR':([4,5,6,29,30,31,],[23,23,-3,-2,-4,23,]),'CAMINAR':([4,5,6,29,30,31,],[24,24,-3,-2,-4,24,]),'MOONWALK':([4,5,6,29,30,31,],[25,25,-3,-2,-4,25,]),'CIRCULO':([4,5,6,29,30,31,],[26,26,-3,-2,-4,26,]),'CUADRADO':([4,5,6,29,30,31,],[27,27,-3,-2,-4,27,]),'END':([5,6,29,30,],[28,-3,-2,-4,]),'SEMICOLON':([7,8,9,10,11,12,13,14,15,16,17,18,42,52,53,54,55,56,57,58,59,60,],[30,-5,-6,-8,-9,-10,-11,-12,-13,-14,-22,-23,-7,-15,-16,-17,-18,-19,-20,-21,-24,-25,]),'PLUS':([7,8,9,10,11,12,13,14,15,16,17,18,42,52,53,54,55,56,57,58,59,60,],[31,-5,-6,-8,-9,-10,-11,-12,-13,-14,-22,-23,31,-15,-16,-17,-18,-19,-20,-21,-24,-25,]),'LPAREN':([19,20,21,22,23,24,25,26,27,],[32,33,34,35,36,37,38,39,40,]),'DOT':([28,],[41,]),'NUMBER':([32,33,34,35,36,37,38,39,40,],[43,44,45,46,47,48,49,50,51,]),'RPAREN':([43,44,45,46,47,48,49,50,51,],[52,53,54,55,56,57,58,59,60,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'sentence_list':([4,],[5,]),'sentence':([4,5,],[6,29,]),'instruction':([4,5,31,],[7,7,42,]),'move_instr':([4,5,31,],[8,8,8,]),'draw_instr':([4,5,31,],[9,9,9,]),'girar':([4,5,31,],[10,10,10,]),'avanzar_vlts':([4,5,31,],[11,11,11,]),'avanzar_ctms':([4,5,31,],[12,12,12,]),'avanzar_mts':([4,5,31,],[13,13,13,]),'rotar':([4,5,31,],[14,14,14,]),'caminar':([4,5,31,],[15,15,15,]),'moonwalk':([4,5,31,],[16,16,16,]),'circulo':([4,5,31,],[17,17,17,]),'cuadrado':([4,5,31,],[18,18,18,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> PROGRAM ID BEGIN sentence_list END DOT','program',6,'p_program','parser.py',17),
  ('sentence_list -> sentence_list sentence','sentence_list',2,'p_sentence_list','parser.py',21),
  ('sentence_list -> sentence','sentence_list',1,'p_sentence_list','parser.py',22),
  ('sentence -> instruction SEMICOLON','sentence',2,'p_sentence','parser.py',26),
  ('instruction -> move_instr','instruction',1,'p_instruction_single','parser.py',30),
  ('instruction -> draw_instr','instruction',1,'p_instruction_single','parser.py',31),
  ('instruction -> instruction PLUS instruction','instruction',3,'p_instruction_combo','parser.py',35),
  ('move_instr -> girar','move_instr',1,'p_move_instr','parser.py',40),
  ('move_instr -> avanzar_vlts','move_instr',1,'p_move_instr','parser.py',41),
  ('move_instr -> avanzar_ctms','move_instr',1,'p_move_instr','parser.py',42),
  ('move_instr -> avanzar_mts','move_instr',1,'p_move_instr','parser.py',43),
  ('move_instr -> rotar','move_instr',1,'p_move_instr','parser.py',44),
  ('move_instr -> caminar','move_instr',1,'p_move_instr','parser.py',45),
  ('move_instr -> moonwalk','move_instr',1,'p_move_instr','parser.py',46),
  ('girar -> GIRAR LPAREN NUMBER RPAREN','girar',4,'p_girar','parser.py',50),
  ('avanzar_vlts -> AVANZAR_VLTS LPAREN NUMBER RPAREN','avanzar_vlts',4,'p_avanzar_vlts','parser.py',56),
  ('avanzar_ctms -> AVANZAR_CTMS LPAREN NUMBER RPAREN','avanzar_ctms',4,'p_avanzar_ctms','parser.py',61),
  ('avanzar_mts -> AVANZAR_MTS LPAREN NUMBER RPAREN','avanzar_mts',4,'p_avanzar_mts','parser.py',66),
  ('rotar -> ROTAR LPAREN NUMBER RPAREN','rotar',4,'p_rotar','parser.py',71),
  ('caminar -> CAMINAR LPAREN NUMBER RPAREN','caminar',4,'p_caminar','parser.py',76),
  ('moonwalk -> MOONWALK LPAREN NUMBER RPAREN','moonwalk',4,'p_moonwalk','parser.py',81),
  ('draw_instr -> circulo','draw_instr',1,'p_draw_instr','parser.py',87),
  ('draw_instr -> cuadrado','draw_instr',1,'p_draw_instr','parser.py',88),
  ('circulo -> CIRCULO LPAREN NUMBER RPAREN','circulo',4,'p_circulo','parser.py',92),
  ('cuadrado -> CUADRADO LPAREN NUMBER RPAREN','cuadrado',4,'p_cuadrado','parser.py',99),
]
